language: python
python:
  - 3.5

addons:
  apt:
    packages:
      - pandoc

notifications:
  email: false

# Install packages
install:
  - "pip install -e .[dev]"

# Run test
script:
  - "py.test tests --cov=stitch --cov-report html --run-slow tests/"
